export const CLOSE_ERR_MSG = 'CLOSE_ERR_MSG'
export const CLOSE_SUCCESS_MSG = 'CLOSE_SUCCESS_MSG';

export const SHOW_ERR_MSG = 'SHOW_ERR_MSG'
export const SHOW_SUCCESS_MSG = 'SHOW_SUCCESS_MSG';

/**********ORG************/
export const SHOW_NEW_ORG = 'SHOW_NEW_ORG';
export const CANCEL_NEW_ORG = 'CANCEL_NEW_ORG';

export const LOAD_ORG = 'LOAD_ORG';
export const LOAD_ORG_SUCCESS = 'LOAD_ORG_SUCCESS';
export const LOAD_ORG_FAIL = 'LOAD_ORG_FAIL';

export const CREATE_ORG = 'CREATE_ORG';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';
export const CREATE_ORG_FAIL = 'LOAD_ORG_FAIL';

export const DELETE_ORG = 'DELETE_ORG';
export const DELETE_ORG_SUCCESS = 'DELETE_ORG_SUCCESS';
export const DELETE_ORG_FAIL = 'DELETE_ORG_FAIL';

/**********GYM************/
export const LOAD_GYM = 'LOAD_GYM';
export const LOAD_GYM_SUCCESS = 'LOAD_GYM_SUCCESS';
export const LOAD_GYM_FAIL = 'LOAD_GYM_FAIL';

export const CREATE_GYM = 'CREATE_GYM';
export const CREATE_GYM_SUCCESS = 'CREATE_GYM_SUCCESS';
export const CREATE_GYM_FAIL = 'CREATE_GYM_FAIL';

export const UPDATE_GYM = 'UPDATE_GYM';
export const UPDATE_GYM_SUCCESS = 'UPDATE_GYM_SUCCESS';
export const UPDATE_GYM_FAIL = 'UPDATE_GYM_FAIL';

export const SHOW_NEW_GYM = 'SHOW_NEW_GYM';
export const CANCEL_NEW_GYM = 'CANCEL_NEW_GYM';

export const CREATE_ACCOUNTING_ROW = 'CREATE_ACCOUNTING_ROW';
export const CREATE_ACCOUNTING_ROW_SUCCESS = 'CREATE_ACCOUNTING_ROW_SUCCESS';
export const CREATE_ACCOUNTING_ROW_FAIL = 'CREATE_ACCOUNTING_ROW_FAIL';

export const CREATE_REIMBURSEMENT = 'CREATE_REIMBURSEMENT';
export const CREATE_REIMBURSEMENT_SUCCESS = 'CREATE_REIMBURSEMENT_SUCCESS';
export const CREATE_REIMBURSEMENT_FAIL = 'CREATE_REIMBURSEMENT_FAIL';

export const PAY_REIMBURSEMENT = 'PAY_REIMBURSEMENT';
export const PAY_REIMBURSEMENT_SUCCESS = 'PAY_REIMBURSEMENT_SUCCESS';
export const PAY_REIMBURSEMENT_FAIL = 'PAY_REIMBURSEMENT_FAIL';

export const LOAD_GYM_ACCOUNTING = 'LOAD_GYM_ACCOUNTING';
export const LOAD_GYM_ACCOUNTING_SUCCESS = 'LOAD_GYM_ACCOUNTING_SUCCESS';
export const LOAD_GYM_ACCOUNTING_FAIL = 'LOAD_GYM_ACCOUNTING_FAIL';

export const LOAD_GYM_REIMBURSEMENT = 'LOAD_GYM_REIMBURSEMENT';
export const LOAD_GYM_REIMBURSEMENT_SUCCESS = 'LOAD_GYM_REIMBURSEMENT_SUCCESS';
export const LOAD_GYM_REIMBURSEMENT_FAIL = 'LOAD_GYM_REIMBURSEMENT_FAIL';

export const LOAD_GYM_SALARY_SETTING = 'LOAD_GYM_SALARY_SETTING';
export const LOAD_GYM_SALARY_SETTING_SUCCESS = 'LOAD_GYM_SALARY_SETTING_SUCCESS';
export const LOAD_GYM_SALARY_SETTING_FAIL = 'LOAD_GYM_SALARY_SETTING_FAIL';

export const UPDATE_GYM_SALARY_SETTING = 'UPDATE_GYM_SALARY_SETTING';
export const UPDATE_GYM_SALARY_SETTING_SUCCESS = 'UPDATE_GYM_SALARY_SETTING_SUCCESS';
export const UPDATE_GYM_SALARY_SETTING_FAIL = 'UPDATE_GYM_SALARY_SETTING_FAIL';

/**********GYM ORDERS************/
export const LOAD_GYM_ORDERS = 'LOAD_GYM_ORDERS';
export const LOAD_GYM_ORDERS_SUCCESS = 'LOAD_GYM_ORDERS_SUCCESS';
export const LOAD_GYM_ORDERS_FAIL = 'LOAD_GYM_ORDERS_FAIL';

/**********GYM SUMMARY************/
export const LOAD_GYM_SUMMARY = 'LOAD_GYM_SUMMARY';
export const LOAD_GYM_SUMMARY_SUCCESS = 'LOAD_GYM_SUMMARY_SUCCESS';
export const LOAD_GYM_SUMMARY_FAIL = 'LOAD_GYM_SUMMARY_FAIL';

/**********HEADER************/
export const SWITCH_GYM = 'SWITCH_GYM';
export const LOAD_LOGGED_IN_COACH_INFO = 'LOAD_LOGGED_IN_COACH_INFO';
export const LOAD_LOGGED_IN_COACH_INFO_SUCCESS = 'LOAD_LOGGED_IN_COACH_INFO_SUCCESS';
export const LOAD_LOGGED_IN_COACH_INFO_FAIL = 'LOAD_LOGGED_IN_COACH_INFO_FAIL';

export const LOAD_UPLOAD_TOKEN = 'LOAD_UPLOAD_TOKEN';
export const LOAD_UPLOAD_TOKEN_SUCCESS = 'LOAD_UPLOAD_TOKEN_SUCCESS';
export const LOAD_UPLOAD_TOKEN_FAIL = 'LOAD_UPLOAD_TOKEN_FAIL';

/**********COACH************/
export const SHOW_NEW_COACH = 'SHOW_NEW_COACH';
export const CANCEL_NEW_COACH = 'CANCEL_NEW_COACH';
export const CREATE_COACH = 'CREATE_COACH';
export const CREATE_COACH_SUCCESS = 'CREATE_COACH_SUCCESS';
export const CREATE_COACH_FAIL = 'CREATE_COACH_FAIL';
export const LOAD_COACH = 'LOAD_COACH';
export const LOAD_COACH_SUCCESS = 'LOAD_COACH_SUCCESS';
export const LOAD_COACH_FAIL = 'LOAD_COACH_FAIL';

/**********WORKLOAD************/
export const LOAD_GYM_AVAILABLE_SLOT = 'LOAD_GYM_AVAILABLE_SLOT'
export const LOAD_GYM_AVAILABLE_SLOT_SUCCESS = 'LOAD_GYM_AVAILABLE_SLOT_SUCCESS'
export const LOAD_GYM_AVAILABLE_SLOT_FAIL = 'LOAD_GYM_AVAILABLE_SLOT_FAIL'

/**********CUSTOMER DETAIL************/
export const LOAD_CUSTOMER_COURSE_BALANCE = 'LOAD_CUSTOMER_COURSE_BALANCE'
export const LOAD_CUSTOMER_COURSE_BALANCE_SUCCESS = 'LOAD_CUSTOMER_COURSE_BALANCE_SUCCESS'
export const LOAD_CUSTOMER_COURSE_BALANCE_FAIL = 'LOAD_CUSTOMER_COURSE_BALANCE_FAIL'

export const LOAD_CUSTOMER_ORDERS = 'LOAD_CUSTOMER_ORDERS'
export const LOAD_CUSTOMER_ORDERS_SUCCESS = 'LOAD_CUSTOMER_ORDERS_SUCCESS'
export const LOAD_CUSTOMER_ORDERS_FAIL = 'LOAD_CUSTOMER_ORDERS_FAIL'

export const LOAD_GROUPED_CUSTOMER_BODY_DATA = 'LOAD_GROUPED_CUSTOMER_BODY_DATA'
export const LOAD_GROUPED_CUSTOMER_BODY_DATA_SUCCESS = 'LOAD_GROUPED_CUSTOMER_BODY_DATA_SUCCESS'
export const LOAD_GROUPED_CUSTOMER_BODY_DATA_FAIL = 'LOAD_GROUPED_CUSTOMER_BODY_DATA_FAIL'

export const LOAD_BODY_DATA_OPTIONS = 'LOAD_BODY_DATA_OPTIONS'
export const LOAD_BODY_DATA_OPTIONS_SUCCESS = 'LOAD_BODY_DATA_OPTIONS_SUCCESS'
export const LOAD_BODY_DATA_OPTIONS_FAIL = 'LOAD_BODY_DATA_OPTIONS_FAIL'

export const DELETE_COACH = 'DELETE_COACH';
export const DELETE_COACH_SUCCESS = 'DELETE_COACH_SUCCESS';
export const DELETE_COACH_FAIL = 'DELETE_COACH_FAIL';

export const BATCH_CREATE_CUSTOMER_DATA = 'BATCH_CREATE_CUSTOMER_DATA';
export const BATCH_CREATE_CUSTOMER_DATA_SUCCESS = 'BATCH_CREATE_CUSTOMER_DATA_SUCCESS';
export const BATCH_CREATE_CUSTOMER_DATA_FAIL = 'BATCH_CREATE_CUSTOMER_DATA_FAIL';

export const CREATE_CUSTOMER_PHOTO = 'CREATE_CUSTOMER_PHOTO';
export const CREATE_CUSTOMER_PHOTO_SUCCESS = 'CREATE_CUSTOMER_PHOTO_SUCCESS';
export const CREATE_CUSTOMER_PHOTO_FAIL = 'CREATE_CUSTOMER_PHOTO_FAIL';

export const DELETE_CUSTOMER_PHOTO = 'DELETE_CUSTOMER_PHOTO';
export const DELETE_CUSTOMER_PHOTO_SUCCESS = 'DELETE_CUSTOMER_PHOTO_SUCCESS';
export const DELETE_CUSTOMER_PHOTO_FAIL = 'DELETE_CUSTOMER_PHOTO_FAIL';

export const LOAD_CUSTOMER_PHOTOS = 'LOAD_CUSTOMER_PHOTOS'
export const LOAD_CUSTOMER_PHOTOS_SUCCESS = 'LOAD_CUSTOMER_PHOTOS_SUCCESS'
export const LOAD_CUSTOMER_PHOTOS_FAIL = 'LOAD_CUSTOMER_PHOTOS_FAIL'

/**********ORDER************/
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const REFUND_ORDER = 'REFUND_ORDER';
export const REFUND_ORDER_SUCCESS = 'REFUND_ORDER_SUCCESS';
export const REFUND_ORDER_FAIL = 'REFUND_ORDER_FAIL';

export const SHOW_NEW_ORDER = 'SHOW_NEW_ORDER';
export const CANCEL_NEW_ORDER = 'CANCEL_NEW_ORDER';

/**********CUSTOMER************/
export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const LOAD_CUSTOMER_SUCCESS = 'LOAD_CUSTOMER_SUCCESS';
export const LOAD_CUSTOMER_FAIL = 'LOAD_CUSTOMER_FAIL';

/**********SCHEDULE************/
export const UPDATE_PENDING_SCHEDULE = 'UPDATE_PENDING_SCHEDULE';

export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const CREATE_SCHEDULE_FAIL = 'CREATE_SCHEDULE_FAIL';

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAIL = 'DELETE_SCHEDULE_FAIL';

export const COMPLETE_SCHEDULE = 'COMPLETE_SCHEDULE';
export const COMPLETE_SCHEDULE_SUCCESS = 'COMPLETE_SCHEDULE_SUCCESS';
export const COMPLETE_SCHEDULE_FAIL = 'COMPLETE_SCHEDULE_FAIL';

export const LOAD_CUSTOMER_SCHEDULE = 'LOAD_CUSTOMER_SCHEDULE';
export const LOAD_CUSTOMER_SCHEDULE_SUCCESS = 'LOAD_CUSTOMER_SCHEDULE_SUCCESS';
export const LOAD_CUSTOMER_SCHEDULE_FAIL = 'LOAD_CUSTOMER_SCHEDULE_FAIL';

export const LOAD_GYM_SCHEDULE = 'LOAD_GYM_SCHEDULE';
export const LOAD_GYM_SCHEDULE_SUCCESS = 'LOAD_GYM_SCHEDULE_SUCCESS';
export const LOAD_GYM_SCHEDULE_FAIL = 'LOAD_GYM_SCHEDULE_FAIL';

export const LOAD_GYM_SCHEDULE_COUNT = 'LOAD_GYM_SCHEDULE_COUNT';
export const LOAD_GYM_SCHEDULE_COUNT_SUCCESS = 'LOAD_GYM_SCHEDULE_COUNT_SUCCESS';
export const LOAD_GYM_SCHEDULE_COUNT_FAIL = 'LOAD_GYM_SCHEDULE_COUNT_FAIL';